# Site settings
title: Yummy Yamin
header-img: img/home-bg.jpg
email: liyamin0222@gmail.com
copyright_name: Yamin Li
description: "Stay young & Stay hungry"
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:  yaminli
facebook_username:  Michael Li
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
